In [15]:
import cv2
import numpy as np
temp1=cv2.imread("star.bmp")#shape we want to match
temp = cv2.cvtColor(temp1, cv2.COLOR_BGR2GRAY)
cv2.imshow("temp",temp)
cv2.waitKey(0)
ta=cv2.imread("star2.bmp")#targeted image
target = cv2.cvtColor(ta, cv2.COLOR_BGR2GRAY)
cv2.imshow("temp1",target)
cv2.waitKey(0)
cv2.destroyAllWindows()
ret,temp1=cv2.threshold(temp,127,255,0)
ret,temp2=cv2.threshold(target,127,255,0)
c,h=cv2.findContours(temp1,cv2.RETR_CCOMP,cv2.CHAIN_APPROX_SIMPLE)
sortedc=sorted(c,key=cv2.contourArea,reverse=True)
tempc=c[2]
print(tempc)
c1,h=cv2.findContours(temp2,cv2.RETR_CCOMP,cv2.CHAIN_APPROX_SIMPLE)
print("target",len(c1))
for x in c1:
    match=cv2.matchShapes(tempc,x,1,0.0)
    print(match)
    if match<0.15:
        closestc=x
        print ("found")
        
    else:
        print("no")
final=cv2.drawContours(target,closestc,-1,(0,100,100),5)
cv2.imshow("output",final)
cv2.waitKey()
cv2.destroyAllWindows()


[[[774 108]]

 [[776 108]]

 [[778 110]]

 ...

 [[771 112]]

 [[772 111]]

 [[772 110]]]
('target', 4)
1.79769313486e+308
no
0.22469917051
no
0.0
found
0.350869055547
no
